version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: studio-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=newsapi
    volumes:
      - mongodb_data:/data/db
    networks:
      - studio-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: studio-app
    restart: unless-stopped
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - PORT=9002
      - HOSTNAME=0.0.0.0
      - MONGODB_URI=mongodb://mongodb:27017/newsapi
      - NEXT_PUBLIC_APP_URL=http://localhost:9002
      - NEXT_PUBLIC_NEWSAPI_KEY=${NEXT_PUBLIC_NEWSAPI_KEY:-your_newsapi_key_here}
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mongodb_data:
    driver: local

networks:
  studio-network:
    driver: bridge
