services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      NODE_ENV: production
      PORT: 3000
      # For server-side fetch requests within the app (e.g. from Server Component to API route)
      # This should be the URL accessible from within the Docker network if services call each other.
      # For calls from client-side, it will be the browser's current host.
      # If running standalone, localhost:3000 is fine for internal SSR fetches from server to itself.
      NEXT_PUBLIC_APP_URL: http://localhost:3000 
      # Add any other environment variables your app needs:
      # EXTERNAL_API_KEY: your_api_key
    # volumes: # Uncomment for development with hot-reloading (not for production image)
    #  - .:/app
    #  - /app/node_modules # Don't mount node_modules from host
    #  - /app/.next    restart: unless-stopped

volumes:
  mongodb_data:
