# Docker Compose para DESARROLLO con hot-reload
# Uso: docker-compose -f docker-compose.dev.yml up

services:
  # Base de datos MongoDB (igual que producción)
  mongodb:
    image: mongo:7.0
    container_name: studio-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: newsapi
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - studio-dev-network

  # Aplicación Next.js en modo desarrollo
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: studio-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/newsapi?authSource=admin
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_NEWSAPI_KEY=${NEXT_PUBLIC_NEWSAPI_KEY:-your_newsapi_key_here}
    volumes:
      # Mount source code for hot-reload
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
    networks:
      - studio-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  studio-dev-network:
    driver: bridge
